/**
 * Official list of barangays in Butuan City, Agusan del Norte, Philippines.
 * Used for auto-suggestion datalists and validation.
 */
export const BUTUAN_BARANGAYS: string[] = [
  "Agao (Poblacion)",
  "Agusan Pequeño",
  "Ambago",
  "Amparo",
  "Ampayon",
  "Anticala",
  "Antongalon",
  "Aupagan",
  "Baan KM 3",
  "Baan Riverside",
  "Babag",
  "Bading",
  "Banza",
  "Baobaoan",
  "Basag",
  "Bayanihan (Poblacion)",
  "Bilay",
  "Bit-os",
  "Bitan-agan",
  "Bobon",
  "Bonbon",
  "Bugabus",
  "Camayahan",
  "Dagohoy (Poblacion)",
  "Dankias",
  "De Oro",
  "Diego Silang (Poblacion)",
  "Doongan",
  "Dulag",
  "Dumalagan",
  "Golden Ribbon",
  "Holy Redeemer",
  "Humabon (Poblacion)",
  "Imadejas",
  "Jose Rizal (Poblacion)",
  "Kinamlutan",
  "Lapu-Lapu (Poblacion)",
  "Lemon",
  "Leon Kilat (Poblacion)",
  "Libertad",
  "Limaha",
  "Los Angeles",
  "Lumbocan",
  "Maguinda",
  "Mahay",
  "Mahogany",
  "Maibu",
  "Mandamo",
  "Manila de Bugabus",
  "Maon",
  "Masao",
  "Maug",
  "New Society Village",
  "Nongnong",
  "Obrero",
  "Ong Yiu",
  "Pagatpatan",
  "Pangabugan",
  "Pianing",
  "Pigdaulan",
  "Pinamanculan",
  "Port Poyohon",
  "Rajah Soliman (Poblacion)",
  "Salvacion",
  "San Ignacio",
  "San Mateo",
  "San Vicente",
  "Santo Niño",
  "Sikatuna (Poblacion)",
  "Silongan (Poblacion)",
  "Sumilihon",
  "Tagabaca",
  "Taguibo",
  "Taligaman",
  "Tandang Sora (Poblacion)",
  "Tiniwisan",
  "Tungao",
  "Urduja (Poblacion)",
  "Villa Kananga",
];
